language: go

go:
  - "1.13"

env:
  global:
    - GO15VENDOREXPERIMENT=1
    - GOOS=linux


install:
  - ./make.sh

script:
  - cd bin
  - md5sum docker-rbd-plugin >> md5.txt
  - sha256sum docker-rbd-plugin >> sha256.txt
  - sha512sum docker-rbd-plugin >> sha512.txt
  - md5sum rbd-snap >> md5.txt
  - sha256sum rbd-snap >> sha256.txt
  - sha512sum rbd-snap >> sha512.txt

deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: ZQfJvpGGNqIdmr0wwAfBaen+4jsBAqcCaXfRrcvokeAuy5GpwwDLV+jVhEAOZr3CoPSZvGE/QYQgWyH47Gcq/hSzMuEcdxgXI82KXSxNG5mHJoJcM2nKufKkfzDgAg3IILkcovTyOSLEajql0s67CKf5bub4pH9ubpWk5nlMwC7Nol7KNhc7De0sPJajyc6ykJPzwbDwiI7HUEUX6nyKkX9BGkbCZjy2pbAZVS0QYdbUbvAzDT+SiljxLlzUhzZGfBUP5xxTac+/bfsn6CWK2tyaOuw4lmAdYZhZJdc6uJZ3Mf9JAZNkb/8aGjg4PEyN3pj00vM/ZGgnCKb64EcAYqx2sfuSd9+SYMy8JuAXSnLLJLaj2GGIm5zi2OWP+uf8URSjPvTe5OPm6CW96NtXnC4df3fK4qb29t8hKiPh+G+BkRsqn2tH37Qwq8u/icrnrWhL01iDMVVai7poqQIN9nNrJE+9hxMOcB1FQkR3gO5gmCpCHi3hfnx3flYJdbyR8I5Qd4u5MA40xJ4nTw75eCksrneGfFfYLf6Be8VPPNP/m6YPBVN8+k5v7yyo9yDt60bmtMXrS0TI6ooWufOw4vgsAqv/Kt+6/32lcy5Ke8U2ORPP9y9guLgmp0LcPewicrGIXZ7Pe9wlNGnvhqBeJlDqyVhn/fK/kF6AFnER/P8=
    file:
      - docker-rbd-plugin
      - rbd-snap
      - md5.txt
      - sha256.txt
      - sha512.txt
    on:
      tags: true
